#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HarvestTracker.Resource", IsApplication=true)]

namespace HarvestTracker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::HarvestTracker.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::HarvestTracker.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::HarvestTracker.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::HarvestTracker.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::HarvestTracker.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::HarvestTracker.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::HarvestTracker.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::HarvestTracker.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::HarvestTracker.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::HarvestTracker.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::HarvestTracker.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::HarvestTracker.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::HarvestTracker.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::HarvestTracker.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::HarvestTracker.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::HarvestTracker.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::HarvestTracker.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::HarvestTracker.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::HarvestTracker.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::HarvestTracker.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::HarvestTracker.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::HarvestTracker.Resource.Layout.test_suite;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int equipment_list = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int field_list = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int OptionHostName = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int OptionPort = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int OptionRemoteServer = 2131099653;
			
			// aapt resource value: 0x7f060015
			public const int OptionsButton = 2131099669;
			
			// aapt resource value: 0x7f060010
			public const int ResultFullName = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int ResultMessage = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int ResultResultState = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int ResultRunSingleMethodTest = 2131099663;
			
			// aapt resource value: 0x7f060013
			public const int ResultStackTrace = 2131099667;
			
			// aapt resource value: 0x7f06000b
			public const int ResultsFailed = 2131099659;
			
			// aapt resource value: 0x7f060008
			public const int ResultsId = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int ResultsIgnored = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int ResultsInconclusive = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int ResultsMessage = 2131099662;
			
			// aapt resource value: 0x7f06000a
			public const int ResultsPassed = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int ResultsResult = 2131099657;
			
			// aapt resource value: 0x7f060014
			public const int RunTestsButton = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int TestSuiteListView = 2131099670;
			
			// aapt resource value: 0x7f060000
			public const int buttonAdd = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int buttonRemove = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int main = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int spinnerEquipmentist = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int spinnerFieldList = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MapView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int options = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int results = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int test_result = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int test_suite = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int buttonAdd = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int buttonRemove = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int equipment_selection = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int field_selection = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
